# Generated by Django 4.0.5 on 2022-07-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.ciudades'),
        ),
    ]
