# Generated by Django 4.0.5 on 2022-07-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_perfil_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
