# Generated by Django 4.0.5 on 2022-08-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_perfil_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to='cedulas'),
        ),
    ]
