# Generated by Django 4.0.5 on 2022-08-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='funcionario',
            field=models.BooleanField(default=False),
        ),
    ]
