# Generated by Django 4.0.5 on 2022-08-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_perfil_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(default='ECUATORIANA', max_length=120),
        ),
    ]
