# Generated by Django 4.0.5 on 2022-08-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0009_perfil_funcionario'),
        ('Registro', '0025_registromunicipal_declaracion_juramentada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioTramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.tramites')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.perfil')),
            ],
        ),
    ]
