# Generated by Django 4.0.5 on 2022-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_tikets_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramites',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
