# Generated by Django 4.0.5 on 2022-07-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_tramites_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramites',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='tramites',
            name='formula',
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registromunicipal',
            name='tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.tramites'),
        ),
    ]
