# Generated by Django 4.0.5 on 2022-07-27 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_remove_tramites_costo_remove_tramites_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='tiket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.tikets'),
        ),
    ]
