# Generated by Django 4.0.5 on 2022-07-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_registromunicipal_tiket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromunicipal',
            name='formula',
        ),
        migrations.AddField(
            model_name='tramites',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
