# Generated by Django 4.0.5 on 2022-07-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0009_remove_registromunicipal_formula_tramites_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tikets',
            name='valor',
        ),
    ]
