# Generated by Django 4.0.5 on 2022-07-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0010_remove_tikets_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='formula',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
