# Generated by Django 4.0.5 on 2022-07-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0011_registromunicipal_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='es_usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
