# Generated by Django 4.0.5 on 2022-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0014_registromunicipal_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromunicipal',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
