# Generated by Django 4.0.5 on 2022-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0015_alter_registromunicipal_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to='cedulas'),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='fot',
            field=models.FileField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='no_adeudar',
            field=models.FileField(blank=True, null=True, upload_to='no_adeudar_municipio'),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='senescyt',
            field=models.FileField(blank=True, null=True, upload_to='senescyt'),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='titulo',
            field=models.FileField(blank=True, null=True, upload_to='titulos'),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='votacion',
            field=models.FileField(blank=True, null=True, upload_to='votacion'),
        ),
    ]
