# Generated by Django 4.0.5 on 2022-08-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0016_registromunicipal_cedula_registromunicipal_fot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
