# Generated by Django 4.0.5 on 2022-08-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0017_registromunicipal_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='direccion_local',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='nombre_negocio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
