# Generated by Django 4.0.5 on 2022-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0018_registromunicipal_direccion_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='ruc',
            field=models.FileField(blank=True, null=True, upload_to='rucs'),
        ),
    ]
