# Generated by Django 4.0.5 on 2022-08-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0020_registromunicipal_x_registromunicipal_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='disenio',
            field=models.FileField(blank=True, null=True, upload_to='letrero'),
        ),
    ]
