# Generated by Django 4.0.5 on 2022-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0021_registromunicipal_disenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='escritura',
            field=models.FileField(blank=True, null=True, upload_to='escritura'),
        ),
    ]
