# Generated by Django 4.0.5 on 2022-08-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0022_registromunicipal_escritura'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='no_adeudar_e',
            field=models.FileField(blank=True, null=True, upload_to='no_adeudar_epaagua'),
        ),
    ]
