# Generated by Django 4.0.5 on 2022-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0024_registromunicipal_primera_vez'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='declaracion_juramentada',
            field=models.FileField(blank=True, null=True, upload_to='declaracion_juramentada'),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='planos',
            field=models.FileField(blank=True, null=True, upload_to='planos'),
        ),
    ]
