# Generated by Django 4.0.5 on 2022-08-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0025_registromunicipal_declaracion_juramentada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='profesion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
