# Generated by Django 4.0.5 on 2022-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0026_registromunicipal_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='registro_profesional',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
