# Generated by Django 4.0.5 on 2022-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0027_registromunicipal_registro_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
