# Generated by Django 4.0.5 on 2022-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0029_registromunicipal_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='calles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='codigo_local',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='codigo_nacional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='este',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='norte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='oeste',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='parroquia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='sector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='sitio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='sur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
