# Generated by Django 4.0.5 on 2022-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0030_registromunicipal_area_registromunicipal_calles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='f_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='n_certificado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='n_comprobante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='nombre_retira',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
