# Generated by Django 4.0.5 on 2022-08-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0031_registromunicipal_f_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='grafico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromunicipal',
            name='puntos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
