# Generated by Django 4.0.5 on 2022-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0033_alter_registromunicipal_grafico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='clave_catastral',
            field=models.CharField(default='00000000000000000000', max_length=200),
        ),
    ]
