# Generated by Django 4.0.5 on 2022-08-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0035_registromunicipal_datos_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromunicipal',
            name='valor_avaluo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
