# Generated by Django 4.0.5 on 2022-08-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0036_registromunicipal_valor_avaluo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromunicipal',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
